config/routes.rb
Rails.application.routes.draw do
  resources :user_tasks

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout
  get '/signin/' => 'sessions#new', as: :signin

  root 'user_tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_tasks, dependent: :destroy
  # Create user from hash from FB API
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
    end
  end
  # Pulls avatar from FB
  def small_image
    "http://graph.facebook.com/#{self.uid}/picture?type=small"
  end

  def normal_image
    "http://graph.facebook.com/#{self.uid}/picture?type=normal"
  end
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  validates :due, presence: true
<<<<<<< HEAD
=======
  belongs_to :user
>>>>>>> release/1.1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Declare a helper method and make it available to controllers and views
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']

    # Look in database for this user, if they don't exist, create them
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)

    # Sets the session user_id
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed out!'
  end

  def new
    
  end
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_task

  # GET /user_tasks
  # GET /user_tasks.json
  def index

  end

  # GET /user_tasks/1
  # GET /user_tasks/1.json
  def show
  end

  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # GET /user_tasks/1/edit
  def edit
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = current_user.user_tasks.build(user_task_params)

    respond_to do |format|
      if @user_task.save
        format.html { redirect_to @user_task }
        format.js
        format.json { render :show, status: :created, location: @user_task }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    respond_to do |format|
      if @user_task.update(user_task_params)
        format.html { redirect_to @user_task }
        format.js {}
        format.json { render :show, status: :ok, location: @user_task }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tasks/1
  # DELETE /user_tasks/1.json
  def destroy
    @user_task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = current_user.user_tasks.find(params[:id])
    end

    def invalid_task
      logger.error "Attempt to access invalid task #{params[:id]}."
      redirect_to user_tasks_url, notice: "Invalid Task"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due, :user_id)
    end

    def all_tasks
      @user_tasks = current_user.user_tasks.order(:due)
    end

    def authenticate!
      redirect_to :sign_in unless current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/_navbar.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li>
      <%= link_to fa_icon('sign-out', text: 'Sign out'), signout_path, id: 'sign_out' %>
    </li>
    <li>
      <%= image_tag current_user.small_image, class: 'img-responsive' %>
    </li>
  <% else %>
    <li>
      <%= link_to fa_icon('sign-in', text: 'Sign in with Facebook'), '/auth/facebook', id: 'sign_in' %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'layouts/navbar' %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user_tasks/_datepicker.js.erb
$(document).ready(function () {
  $('#user_task_due').datepicker({
    autoclose: true,
    todayHighLight: true,
    toggleActive: true,
    format: "yyyy-mm-dd",
    orientation: "top-auto"
  });
});

app/views/user_tasks/_form.html.erb
<%= simple_form_for(@user_task, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description, as: :text, placeholder: 'Make groceries' %>
    <%= f.input :due, as: :string, placeholder: 'Today' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_tasks/_user_task.html.erb
<div class="well">
  <span class="task">
    <%= link_to user_task.description, user_task,
                remote: true, method: :delete,
                data: { confirm: "Are you sure?"} %>
  </span>
  <%= link_to fa_icon('pencil'), edit_user_task_path(user_task), remote: true %>
  <span class="pull-right">
    <% unless user_task.due.nil? %>
      <%= user_task.due.stamp('12 Feb 2017') %>
    <% end %>
  </span>
</div>

app/views/user_tasks/create.js.erb
$('#tasks').html('<%= j (render @user_tasks) %>');

$('#task-form').slideUp(350);

app/views/user_tasks/destroy.js.erb
$('#tasks').html('<%= j (render @user_tasks) %>');

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form', user_task: @user_task %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/edit.js.erb
$('#task-form')
  .html('<%= j (render 'form') %>')
  .slideDown(350);


<%= render 'datepicker' %>

app/views/user_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Tasks</h1>

<%= link_to 'New User Task', new_user_task_path, remote: true, class: 'btn btn-default' %>
<br><br>
<div id="task-form">

</div>
<br>
<div id="tasks">
  <%= render @user_tasks %>
  <% if @user_tasks.empty? %>
     <img src="https://i.imgflip.com/pp7dt.jpg" />
  <% end %>
</div>

app/views/user_tasks/new.html.erb
<h2>Sign In</h2>

<%= link_to fa_icon('sign-in', text: 'Sign In With Facebook'), '/auth/facebook', id: 'sign_in' %>

app/views/user_tasks/new.js.erb
$('#task-form')
  .html('<%= j (render 'form') %>')
  .slideDown(350);

<%= render 'datepicker' %>

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/update.js.erb
$('#tasks').html(' <%= j (render @user_tasks) %>');

$('#task-form').slideUp(350);